CREATE TABLE `BARCODE_A` (`SUPPLIER_ID` int(11) DEFAULT NULL,`SKU` varchar(20) DEFAULT NULL,`BARCODE` varchar(45) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `CATALOG_A` (`SKU` varchar(20) NOT NULL,`DESCRIPTION` varchar(200) DEFAULT NULL,PRIMARY KEY (`SKU`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `SUPPLIERS_A` (`ID` int(11) NOT NULL,`NAME` varchar(200) DEFAULT NULL,PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
---
CREATE TABLE `CATALOG_B` (`SKU` varchar(20) NOT NULL,`DESCRIPTION` varchar(200) DEFAULT NULL,PRIMARY KEY (`SKU`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `BARCODE_B` (`SUPPLIER_ID` int(11) DEFAULT NULL,`SKU` varchar(20) DEFAULT NULL,`BARCODE` varchar(45) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `SUPPLIERS_B` (`ID` int(11) NOT NULL,`NAME` varchar(200) DEFAULT NULL,PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;







